### ISSUE TITLE
To-Do following the Port Zero Lunch & Learn

### ISSUE THREAD

**Issue by Dzol** [Dzol/cordial#1]
- [ ] Revise function signature for `M.f/2` or change which function is referred to
- [ ] Talk about LIFO/FIFO properties
- [ ] List John Hughes' talks
- [ ] Find a place for the Google story
- [ ] List examples of using pictures to find properties
